apiVersion: v1
kind: Pod
metadata:
   name: flask-pod
   labels:
      app: flask-demo
      environment: demo

spec:
   containers:
      - name: flask-container
        image: jack17kdb/flask-demo:latest
        ports:
          - containerPort: 5000
